name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  #20

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

      # - name: Build Docker image
      #   if: success()
      #   run: docker build -t nodejs-docker-ci-cd .

      - name: Log in to Docker Hub
        if: success() && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        if: success()
        run: docker build -t nodejs-docker-ci-cd .