name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  #20

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

      - name: Build Docker image
        if: success()
        run: docker build -t nodejs-docker-ci-cd .